#!/usr/bin/env bash
export username=$lpass_username
if [[ -z $username ]]; then
	>&2 echo 'lpass_username variable not set'
	exit 1
fi

#attempt login
is_logged=$(lpass status)
if [[ $is_logged == N* ]]; then
	result=$(lpass login --trust $username)
	if [[ $result == F* ]]; then
		exit 0
	fi
fi


selection=`lpass ls --format="%an/%au" | rofi -show -dmenu` 
if [[ -z $selection ]]; then
	exit 0
fi

username=`grep -oE "[^/]+$" <<< "$selection"`
website=`grep -oE "^.+/" <<< "$selection"`
website=${website::-1}

#get id of username/password combo
id=`lpass ls --format="%an/%au/%ai" | grep  $website | grep $username | grep -oE "[^/]+$"`
if [[ -n $id ]]; then
	lpass show -c --password $id &
fi
